/** 与 `scripts/it-category-seed.json` 中叶子分类 name 完全一致；topics 供大模型扩写成正文与评论。
 * 每个分类 topics.length 须与 synthetic-it-constraints.ts 中 SYNTHETIC_POSTS_PER_CATEGORY_* 一致（当前为每类 16～60 篇）。 */
export type CategoryOutline = {
  categoryName: string;
  /** externalKey 前缀：字母数字 */
  keyPrefix: string;
  topics: string[];
};

export const SYNTHETIC_IT_OUTLINES: CategoryOutline[] = [
  {
    categoryName: "后端",
    keyPrefix: "be",
    topics: [
      "REST 接口设计：PUT/PATCH 语义、幂等与客户端重试",
      "JWT：签名校验、过期与吊销难点；Cookie 存令牌与 XSS 关系简述",
      "服务端数据库连接池容量与尾延迟、云数据库连接数配额",
      "Redis：缓存穿透、击穿、雪崩的含义与常见对策",
      "分布式 tracing：trace id / span 在跨服务排障中的作用",
      "gRPC 与 REST 的典型选型场景与契约演进注意点",
      "对外 API 版本控制、弃用公告（deprecation）与客户迁移窗口",
      "网关限流、熔断与服务降级如何协作保护上游",
      "GraphQL 与 REST 并存时的字段解析治理与缓存分层直觉",
      "Webhook 投递失败：重试退避、签名校验与时间戳防重放要点",
      "分页接口 cursor 相对 offset 的典型取舍与深分页风险意识",
      "SSE 与 WebSocket：连接KeepAlive、背压与横向扩容简介（概念）",
      "消息队列至少一次投递下的幂等消费键与业务去重表思路",
      "OpenAPI 契约、文档站点与代码生成工具的边界（不写臆造工具链细节）",
      "数据库迁移脚本（Flyway/Liquibase）与在线 DDL 风险的团队纪律（概念）",
      "Kubernetes liveness/readiness 探针与健康检查的适用边界简介",
    ],
  },
  {
    categoryName: "前端",
    keyPrefix: "fe",
    topics: [
      "Vue 3 Composition API 与 composable 复用思路",
      "浏览器事件循环：宏任务、微任务与渲染调度（概念）",
      "内容安全策略 CSP 如何减轻 XSS 风险（概念）",
      "Web Vitals：LCP、INP、CLS 含义（面向体验指标）",
      "TypeScript strictNullChecks / noImplicitAny 的工程收益",
      "无障碍：语义化控件与 aria 的常见误区",
      "前端路由 history 与 hash 模式的利弊与部署约束",
      "CSS 层叠、BEM 与 utility-first（如 Tailwind）的工程取舍",
      "Vite 与 webpack：本地开发体验与产物拆分心智差异（概念）",
      "SSR/CSR 水合不匹配常见成因与排查直觉（不写臆造框架版本结论）",
      "Service Worker 缓存策略与更新生命周期简介（概念）",
      "localStorage 与 sessionStorage：容量、同源与安全注意点",
      "ESLint、Prettier 与 CI 门禁的配合方式（不以某一服务商为准）",
      "前端 i18n：占位长度、复数规则与文案管理工作量直觉",
      "source map 在生产环境的暴露面与排障权衡（概念）",
      "Web Worker 适合搬运的计算类型与不合适的场景直觉",
    ],
  },
  {
    categoryName: "Android",
    keyPrefix: "and",
    topics: [
      "Activity 生命周期与屏幕旋转时的状态保存思路",
      "Kotlin 协程 Dispatcher 选择与结构化并发简介",
      "Jetpack Compose 重组（recomposition）直觉解释",
      "R8/ProGuard：混淆、裁剪与反射/序列化的注意点",
      "Android 运行时权限：请求时机与 rationale",
      "RecyclerView ViewHolder 与 DiffUtil 的目的",
      "WorkManager 适用场景与系统后台任务约束",
      "Material 主题与深色模式（Dark Theme）适配要点",
      "Fragment 与 Navigation 组件分工的典型心智模型（概念）",
      "Kotlin Flow 相对 LiveData 的工程选型直觉（不写单一结论）",
      "Room 迁移：破坏性变更与数据保全的讨论要点（概念）",
      "Bitmap 解码与大图加载：内存峰值与采样直觉（概念）",
      "动态交付与应用模块化对发布节奏的影响简介（概念）",
      "App Startup：初始化链路收敛与冷启动观测直觉",
      "WebView 与原生桥的安全边界：可信来源与白名单（概念）",
      "APK/AAB 体积分析与裁剪切入点简介（概念）",
    ],
  },
  {
    categoryName: "iOS",
    keyPrefix: "ios",
    topics: [
      "Swift async/await 与主线程/Actor 的基本心智模型",
      "UIViewController 生命周期钩子在何时做事更合适",
      "ARC：循环引用与 weak/unowned 的选择",
      "URLSession：取消请求与 ATS（HTTPS）注意点",
      "SwiftUI：@State、@StateObject、@ObservedObject 易混点",
      "隐私清单与敏感权限说明文案的重要性（合规视角）",
      "Combine 框架与异步事件流的背压直觉（概念）",
      "Keychain 存令牌时的可访问性级别与安全权衡",
      "SwiftUI Previews 与快照测试简介：定位与局限（概念）",
      "UITableView 与 UICollectionView 选型时的列表复杂度直觉",
      "推送通知权限请求与用户价值对齐的常见误区（概念）",
      "Core Data 与 SwiftData：迁移成本的心智负担简介（概念）",
      "App Thinning 与按需资源的基本直觉（概念）",
      "Background Tasks：配额与系统调度的不确定性（概念）",
      "Universal Links 与深度链接调试要点简介（概念）",
      "XCTest/UI 测试稳定性：异步与等待的常见痛点（概念）",
    ],
  },
  {
    categoryName: "人工智能",
    keyPrefix: "ai",
    topics: [
      "监督学习 / 无监督学习 / 半监督与自监督的概念分界",
      "过拟合、验证集与测试集的角色；常见缓解手段",
      "Transformer 自注意力机制的直观解释（不写臆造公式推导）",
      "梯度消失/爆炸与初始化、归一化的关系（概念）",
      "精度、召回率与不均衡分类的阅读方式",
      "推理延迟与量化、蒸馏等压缩路径（概念）",
      "标注噪声、质检流程与主动学习简介（概念）",
      "线上模型监控与数据漂移（concept drift）的阅读方式",
      "交叉验证与网格搜索的职责分界（概念层面）",
      "F1-score 与 ROC-AUC：适用阅读场景差异（概念）",
      "正则化 L1/L2 与稀疏解直觉（不写臆造公式推导）",
      "子词 tokenization 对中文处理的常见影响（概念）",
      "BatchNorm 与 LayerNorm 的常见放置差异（概念）",
      "Early stopping 与验证曲线的判读直觉（概念）",
      "伪标签与半监督流程的工程风险意识（概念）",
      "线上 A/B：多重比较与样本量直觉（不写臆造统计公式）",
    ],
  },
  {
    categoryName: "数据库",
    keyPrefix: "db",
    topics: [
      "InnoDB B+树索引为什么常用范围扫描（直觉）",
      "事务隔离级别与脏读、不可重复读、幻读（教材定义层面）",
      "覆盖索引（covering index）是什么",
      "慢查询与 EXPLAIN：从哪里下手排查",
      "主从复制延迟带来的「读后读」一致性风险",
      "范式化与反范式化的工程权衡",
      "读写分离与中间件路由：何时读主、何时读从",
      "分区表适用场景与 DDL、归档运维的注意点",
      "Online DDL 工具链（gh-ost 等）适用边界简介（概念）",
      "MVCC 与快照读的直觉解释（不以某一数据库版本为准）",
      "索引选择性与最左前缀原则回顾（教材层面）",
      "binlog row 与 statement 格式的取舍简介（概念）",
      "读写线程池打满的征兆观察与排队直觉（概念）",
      "全文检索相对 LIKE 前缀索引的典型场景差异（概念）",
      "备份加密与密钥轮转的注意点（不写臆造合规条文）",
      "分布式数据库扩展与单机 OLTP 的差异心智（概念）",
    ],
  },
  {
    categoryName: "程序开发",
    keyPrefix: "dev",
    topics: [
      "语义化版本 SemVer：MAJOR.MINOR.PATCH",
      "Git merge 与 rebase 的典型适用场景",
      "CI：分层测试与缓存制品缩短反馈环",
      "代码评审：区分阻塞问题与风格偏好",
      "特性开关（feature flag）与渐进发布",
      "结构化日志相对纯文本排障的优势",
      "契约测试与消费者驱动契约（CDC）简介",
      "制品仓库与依赖漏洞扫描在 CI 中的位置",
      "Monorepo 与多仓发布的协作摩擦点简介（概念）",
      "Trunk-based 与长生命周期特性分支的权衡直觉（概念）",
      "SBOM 与许可证合规在 CI 中的位置简介（概念）",
      "机密管理：避免把密钥写入仓库的团队纪律（概念）",
      "Makefile/Taskfile：脚本化可读性与可移植性直觉（概念）",
      "混沌工程与故障演练的最小可行步骤简介（概念）",
      "SLO/SLI/错误预算与发布节奏的直觉关系（概念）",
      "On-call 轮值与事后复盘模板要点简介（概念）",
    ],
  },
];
